apiVersion: v1
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mysqld_safe_syslog.cnf: |
    [mysqld_safe]
    skip_log_error
    syslog
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: conf-d
  namespace: ctfd
