apiVersion: v1
data:
  docker.cnf: |
    [mysqld]
    skip-host-cache
    skip-name-resolve
  mysqld_safe_syslog.cnf: |
    [mysqld_safe]
    skip_log_error
    syslog
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"docker.cnf":"[mysqld]\nskip-host-cache\nskip-name-resolve\n","mysqld_safe_syslog.cnf":"[mysqld_safe]\nskip_log_error\nsyslog\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":null,"name":"conf-d","namespace":"ctfd"}}
  name: conf-d
  namespace: ctfd
